# Generated by Django 4.0.4 on 2022-06-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_cartitem_options_product_color_code'),
        ('payment_module', '0002_invoice_invoicedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceDetails',
            new_name='InvoiceDetail',
        ),
    ]
