# Generated by Django 4.0.4 on 2022-06-18 16:30

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0003_rename_invoicedetails_invoicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
