# Generated by Django 4.0.4 on 2022-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0006_invoice_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
