# Generated by Django 4.0.4 on 2022-06-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0008_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
    ]
