# Generated by Django 4.0.4 on 2022-06-18 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0009_remove_invoice_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
